# Generated by Django 6.0.4 on 2026-04-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_vente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={},
        ),
    ]
