# Generated by Django 6.0.4 on 2026-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_vente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
